#!/bin/bash

. bootrr

TEST_CASE_ID="$1"
DRIVER="$2"
DEVICE="$3"
TIMEOUT="${4:-1}"

if [ -z "${TEST_CASE_ID}" -o -z "${DRIVER}" -o -z "${DEVICE}" ]; then
	echo "Usage: $0 <test-case-id> <driver> <device> [<timeout>]"
	exit 1
fi

timeout ${TIMEOUT} [ -d /sys/bus/*/drivers/${DRIVER} ] || test_report_exit blocked

# If the device parameter is a glob pattern, run the test for each
# device once expanded
devices=(/sys/bus/*/drivers/${DRIVER}/${DEVICE})
for path in "${devices[@]}"; do
    timeout ${TIMEOUT} [ -L $path ] || test_report_exit fail
done

test_report_exit pass
