#!/bin/sh

# UART
assert_driver_present pl011-driver-present uart-pl011
assert_device_present ttyAMA0-probed uart-pl011 20201000.*

# RNG
assert_driver_present bcm2835-rng-driver-present bcm2835-rng
assert_device_present rng-probed bcm2835-rng 20104000.*

# I2C
assert_driver_present bcm2835-i2c-driver-present i2c-bcm2835
assert_device_present i2c0-probed i2c-bcm2835-i2c 20804000.*
assert_device_present i2c1-probed i2c-bcm2835-i2c 20805000.*

# Watchdog
assert_driver_present bcm2835-wdt-driver-present bcm2835-wdt
assert_device_present watchdog-probed bcm2835-wdt bcm2835-wdt

# Hardware monitoring
assert_driver_present bcm2835-thermal-driver-probed bcm2835_thermal
assert_device_present thermal-probed bcm2835_thermal 20212000.*

assert_driver_present raspberrypi-hwmon-driver-present raspberrypi-hwmon
assert_device_present raspberrypi-hwmon-probed raspberrypi-hwmon raspberrypi-hwmon

# SDHCI
assert_driver_present sdhost-bcm2835-driver-probed sdhost-bcm2835
assert_device_present mmc0-probed sdhost-bcm2835 20202000.*

# USB
assert_driver_present dwc2-driver-present dwc2
assert_device_present usbotg-probed dwc2 20980000.*

# Ethernet
assert_driver_present smsc95xx-driver-present smsc95xx
assert_device_present eth0-probed smsc95xx 1-1.1:1.0

# Display
assert_driver_present vc4-crtc-driver-present vc4_crtc
assert_device_present pixelvalve0-probed vc4_crtc 20206000.*
assert_device_present pixelvalve1-probed vc4_crtc 20207000.*
assert_device_present pixelvalve2-probed vc4_crtc 20807000.*

assert_driver_present vc4-txp-driver-present vc4_txp
assert_device_present vc4-txp-probed vc4_txp 20004000.*

assert_driver_present vc4-hvs-driver-present vc4_hvs
assert_device_present vc4-hvs-probed vc4_hvs 20400000.*

assert_driver_present vc4-drm-driver-present vc4-drm
assert_device_present vc4-drm-probed vc4-drm soc:gpu

# cpufreq
assert_cpufreq_enabled cpufreq-enabled 1
